
remote_theme: mmistakes/so-simple-theme@3.2.0
skin: "/assets/css/skins/dark.css"
locale: en-US
title: "What's Prerna Cooking"
description: "A Pandemic-Induced Recipe Website"
baseurl: 
url: http://prernaadvani.github.io
logo: /images/WPC Logo.png
date_format: "%B %-d, %Y"

google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

disqus:
  shortname: prernaadvani
twitter:
  username: prerna206


liquid:
  error_mode: strict

permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml


paginate: 9
paginate_path: /page:num/

# Search
search_full_content: true 

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: true
      share: true

# Site Author
author:
  name: Prerna Advani
  picture: https://raw.githubusercontent.com/prernaadvani/prernaadvani.github.io.temp/master/images/IMG_0466.jpg
  email: prerna206@hotmail.com
  twitter: prerna206
  links:
    - title: Email
      url: mailto:prerna206@hotmail.com
      icon: fas fa-envelope

#Footer links:
footer_links:
  - title: Email
    url: mailto:prerna206@hotmail.com
    icon: fas fa-envelope
  - title: Twitter
    url: https://twitter.com/prerna206
    icon: fab fa-twitter-square
  - title: LinkedIn
    url: https://www.linkedin.com/in/prernaadvani/
    icon: fab fa-linkedin
  
 
copyright: ""
